#  飞书
APP_ID: cli_a4a4dd8ba7b3d00b
APP_SECRET: 5ijdWvy2IyclUEAvPjxWneDbNPQnkkCT
APP_ENCRYPT_KEY: EetkpCxoYBStnAupVHCMIb56OPMAL23X
APP_VERIFICATION_TOKEN: 1IcP0l9iIOjcEq2JiYtAFfpzVOnAk8jK
# 请确保和飞书应用管理平台中的设置一致 
BOT_NAME: OpenAI
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: 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
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""
