#  飞书
APP_ID: cli_a4a7a56fac38100d
APP_SECRET: oemw7kLibjVCi1eXGHGzybZ15GFeCMlM
APP_ENCRYPT_KEY: VEwytW8ySVP1zdVbfqoOFdFYQ7boBxXN
APP_VERIFICATION_TOKEN: vKKYlfQ1nWZTR1xfUGc2sece3kODxSNZ
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: ChatGPT
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: 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,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,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
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""
